365 tensorflow upgrade nn hack
NifTK/NiftyNet pull request #380
Opened 2019-06-05 13:52 UTC by danieltudosiu

## Status
READY

## Description
NiftyNet was tested if it works with Tensorflow 1.13.1/1.14.0rc0 and CUDA 10.0.130 with cudnn 7.5.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)
- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.

## Todos
- [x] Tests
- [x] Documentation

## Impacted Areas in Application
List general components of the application that this PR will affect:
niftynet
    |
    -layer
    |   |
    |   -crf.py
    |
    -contrib
    |   |
    |   -segmentation_selective_sampler
    |       |
    |       -test_sampler_selective.py
    -io
        |
        -misc_io.py
tests
    |
    -most tests (too lazy to put 25+ files in the nice format I used)

2019-06-05 14:01 UTC, ericspod commented on tests/niftynet_testcase.py
> +    pass
Newline here.

2019-06-05 14:01 UTC, ericspod commented on tests/niftynet_testcase.py
> +    delattr(tf.test.TestCase,'test_session')
Add a comment here stating why we've had to do this.

2019-06-05 14:04 UTC, ericspod commented on niftynet/io/misc_io.py
> +    try:
I would comment here that this is needed for compatibility reasons between TF versions

2019-06-05 14:06 UTC, ericspod commented on requirements-gpu.txt
> +numpy>=1.16.4
I would have numpy>=1.13.3

2019-06-05 14:06 UTC, ericspod commented on requirements-gpu.txt
> +tensorflow-gpu==1.14.0rc0
I would have >=1.12.2

2019-06-05 14:09 UTC, ericspod requested changes
Other than adding a few more comments I would say this is good to go.

2019-06-05 14:29 UTC, ericspod requested changes
In the added comments, "brake" -> "break" but otherwise good. There are conflicts with other tests that were modified today before the PR was made. The tests are also failing because CUDA 10  isn't getting loaded on the host VM. We need to set the requirements for now to be TF 1.12 as they were before, we know that the test will work on later versions and will have to return to upgrading the test host.

2019-06-10 10:25 UTC, danieltudosiu commented
@ericspod what are we doing with this pull request?

2019-06-13 12:59 UTC, danieltudosiu commented
So what should we do based on the Tensorflow Issue [Unittest and test_session interaction #29439](https://github.com/tensorflow/tensorflow/issues/29439) response? Change the tests naming scheme so we do not use the non-OOP fix?

2019-06-14 13:44 UTC, ericspod commented
It wasn't our names it was theirs that was the issue. I say we keep our
delattr solution for now.

Eric

On Thu, 13 Jun 2019, 14:59 Petru-Daniel Tudosiu <notifications@github.com
wrote:

> So what should we do based on the Tensorflow Issue Unittest and
> test_session interaction #29439
> <https://github.com/tensorflow/tensorflow/issues/29439> response? Change
> the tests naming scheme so we do not use the non-OOP fix?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NifTK/NiftyNet/pull/380?email_source=notifications&email_token=AEHHUWQFHTNIZ34TQZ4LNY3P2JACTA5CNFSM4HTYIG5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXTTMRY#issuecomment-501691975>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AEHHUWURWJ2FSKCQ7QDPKQDP2JACTANCNFSM4HTYIG5A>
> .
>

2019-06-17 10:37 UTC, ericspod approved these changes

2019-06-17 14:04 UTC, merged